### ISSUE TITLE
player links are broken

### ISSUE THREAD

**Issue by howardchung** [odota/carry#3]
~Tries to go to: https://https//www.opendota.com/logout~

Top donaters (https://carry.opendota.com/) are linked to the wrong page. Their names link to "https://carry.opendota.com/players/111111" instead of "https://opendota.com/players/11111"

**Comment by howardchung** [comment]
Top left logo is also broken, trying to go to: http://https//www.opendota.com

I think the host variable is not passed down properly.

**Comment by albertcui** [comment]
Think this is fixed.

**Comment by howardchung** [comment]
Player links still broken

**Comment by albertcui** [comment]
Fixed.
